### ISSUE TITLE
can't find Zlib on Fedora 33

### ISSUE THREAD

**Issue by n1trux** [xbmc/audiodecoder.openmpt#19]
There's a step in the build script which checks for ZLIB, but can't find it, even though `zlib` and `zlib-devel` are both installed in version 1.2.11.

Building fails on Fedora 33 in consequence.

**Comment by AlwinEsch** [comment]
How is it at the moment? Can you give a full build log to see what happens exact?

**Comment by AlwinEsch** [comment]
Closed as no further problems reported.
